yarnPath: .yarn/releases/yarn-3.4.1.cjs
nodeLinker: node-modules

npmScopes:
  lunaproject-discord:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.pkg.github.com'

npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: true
    npmAuthToken: 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
