yarnPath: .yarn/releases/yarn-3.6.3.cjs
nodeLinker: node-modules

npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: true
    npmAuthToken: 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

npmScopes:
  lunaproject-discord:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"
