nodeLinker: node-modules
npmScopes:
  tiptap-pro:
    npmAlwaysAuth: true
    npmAuthToken: kFi1Qr23Z6jZEpvsR23AFrjCPXWfpr2DlmrRj+M8y0+yiwULptuI6fOeZKUbCK0G
    npmRegistryServer: "https://registry.tiptap.dev/"

yarnPath: .yarn/releases/yarn-4.6.0.cjs
