import { ReactNode } from 'react';

export type LocaleType = 'ja' | 'en';

export type TranslationKeys =
    'success'
    | 'warning'
    | 'error'
    | 'info'
    | 'loading'
    | 'login'
    | 'logout'
    | 'yes'
    | 'no'
    | 'enabled'
    | 'disabled'
    | 'default'
    | 'add'
    | 'remove'
    | 'create'
    | 'delete'
    | 'edit'
    | 'confirm'
    | 'cancel'
    | 'save'
    | 'reset'
    | 'discard_changes'
    | 'open'
    | 'close'
    | 'move_up'
    | 'move_down'

    | 'guild'
    | 'guilds'
    | 'channel'
    | 'channels'
    | 'role'
    | 'roles'
    | 'member'
    | 'members'
    | 'user'
    | 'users'


    | 'pattern_date'
    | 'pattern_time'
    | 'pattern_datetime'


    | 'search'
    | 'search_channels'
    | 'search_roles'
    | 'search_members'


    | 'embeds'
    | 'embed'
    | 'embed_add'
    | 'embed_author'
    | 'embed_author_name'
    | 'embed_author_url'
    | 'embed_author_icon_url'
    | 'embed_body'
    | 'embed_body_title'
    | 'embed_body_description'
    | 'embed_body_url'
    | 'embed_body_color'
    | 'embed_fields'
    | 'embed_field'
    | 'embed_field_add'
    | 'embed_field_name'
    | 'embed_field_value'
    | 'embed_field_inline'
    | 'embed_image'
    | 'embed_image_image_url'
    | 'embed_image_thumbnail_url'
    | 'embed_footer'
    | 'embed_footer_text'
    | 'embed_footer_icon_url'
    | 'embed_footer_timestamp'


    | 'error_unauthorized_title'
    | 'error_unauthorized_description'
    | 'error_forbidden_title'
    | 'error_forbidden_description'
    | 'error_not_found_title'
    | 'error_not_found_description'


    | 'welcome'
    | 'welcome_to_name'


    | 'home'
    | 'status'
    | 'leaderboard'
    | 'choose_guild_leaderboard'


    | 'guild_settings'
    | 'choose_guild_settings'
    | 'settings_basic'
    | 'settings_guild_management'
    | 'settings_features_and_options'

    | 'prefix_and_nickname'
    | 'prefix_and_nickname_description'
    | 'prefix'
    | 'nickname'
    | 'nickname_hint'

    | 'time_and_language'
    | 'guild_time_and_language_description'
    | 'date_and_time'
    | 'timezone'
    | 'timezone_description'
    | 'guild_language_description'

    | 'commands'
    | 'commands_description'
    | 'commands_permissions_channels'
    | 'commands_permissions_all_channels'
    | 'commands_permissions_roles'
    | 'commands_permissions_all_roles'
    | 'commands_permissions_members'
    | 'command_manage'
    | 'command_enabled'
    | 'command_user_permissions'
    | 'command_bot_permissions'
    | 'command_permissions_channels'
    | 'command_permissions_roles'
    | 'command_permissions_members'

    | 'welcome_message'
    | 'welcome_message_description'
    | 'welcome_message_enabled'
    | 'welcome_message_edit_description'
    | 'welcome_message_edit_hint'

    | 'goodbye_message'
    | 'goodbye_message_description'
    | 'goodbye_message_enabled'
    | 'goodbye_message_edit_description'
    | 'goodbye_message_edit_hint'

    | 'activity'
    | 'activity_description'
    | 'activity_enabled'
    | 'activity_manage_roles'
    | 'activity_type'
    | 'activity_type_playing_long'
    | 'activity_type_playing_short'
    | 'activity_type_playing_description'
    | 'activity_type_streaming_long'
    | 'activity_type_streaming_short'
    | 'activity_type_streaming_description'
    | 'activity_type_listening_long'
    | 'activity_type_listening_short'
    | 'activity_type_listening_description'
    | 'activity_type_watching_long'
    | 'activity_type_watching_short'
    | 'activity_type_watching_description'
    | 'activity_type_custom_status_long'
    | 'activity_type_custom_status_short'
    | 'activity_type_custom_status_description'

    | 'role_panels'

    | 'level'
    | 'experience'
    | 'rank'
    | 'level_description'
    | 'level_enabled'
    | 'level_experience_per_message'
    | 'level_manage'
    | 'level_manage_disabled_channels_description'
    | 'level_manage_disabled_roles_description'
    | 'level_reward'
    | 'level_reward_type'
    | 'level_reward_type_stack'
    | 'level_reward_type_stack_description'
    | 'level_reward_type_replace'
    | 'level_reward_type_replace_description'
    | 'level_reward_remove_role_demoted'
    | 'level_reward_manage_roles'
    | 'level_notification'
    | 'level_notification_type'
    | 'level_notification_type_disabled'
    | 'level_notification_type_direct_message'
    | 'level_notification_type_latest_channel'
    | 'level_notification_type_custom_channel'
    | 'level_notification_channel'
    | 'level_notification_edit_description'
    | 'level_notification_edit_hint'
    | 'level_leaderboard'
    | 'level_leaderboard_view'
    | 'level_leaderboard_public'
    | 'level_leaderboard_allow_join'
    | 'level_leaderboard_vanity_code'

    | 'translate'
    | 'translate_description'
    | 'translate_enabled'
    | 'translate_reaction'
    | 'translate_manage_disabled_channels_description'
    | 'translate_manage_disabled_roles_description'

    | 'vote'
    | 'vote_description'
    | 'vote_enabled'
    | 'quote'
    | 'quote_description'
    | 'quote_enabled'
    | 'quote_reaction'
    | 'quote_message'
    | 'quote_other_guild_to_this_guild'
    | 'quote_this_guild_to_other_guild'
    | 'quote_manage_disabled_channels_description'
    | 'quote_manage_disabled_roles_description'

    | 'music'
    | 'music_description'
    | 'music_enabled'
    | 'music_web_panel'
    | 'music_default_volume'
    | 'music_timeout_seconds'
    | 'music_next_media_notification'
    | 'music_next_media_notification_description'
    | 'music_sources'
    | 'music_source_youtube'
    | 'music_source_niconico'
    | 'music_source_soundcloud'
    | 'music_source_twitch'
    | 'music_source_bandcamp'
    | 'music_source_vimeo'

    | 'text_to_speech'

    | 'logging'
    | 'logging_description'
    | 'logging_enabled'
    | 'logging_channel'
    | 'logging_moderation'
    | 'logging_moderation_update'
    | 'logging_moderation_kick'
    | 'logging_moderation_prune'
    | 'logging_moderation_ban'
    | 'logging_moderation_unban'
    | 'logging_member'
    | 'logging_member_join'
    | 'logging_member_leave'
    | 'logging_member_update'
    | 'logging_member_role_add'
    | 'logging_member_role_remove'
    | 'logging_voice'
    | 'logging_voice_join'
    | 'logging_voice_leave'
    | 'logging_voice_move'
    | 'logging_voice_mute'
    | 'logging_voice_deafen'
    | 'logging_category'
    | 'logging_text_channel'
    | 'logging_voice_channel'
    | 'logging_channel_permission_update'
    | 'logging_role'
    | 'logging_emote'
    | 'logging_invite'
    | 'logging_webhook'
    | 'logging_integration'
    | 'logging_object_create'
    | 'logging_object_delete'
    | 'logging_object_update'
    | 'logging_message'
    | 'logging_message_update'
    | 'logging_message_delete'
    | 'logging_message_purge'
    | 'logging_message_pin'
    | 'logging_message_unpin'


    | 'user_settings'
    | 'user_time_and_language_description'
    | 'user_language_description'


    | 'send_message_channel'
    | 'manage_disabled_channels'
    | 'manage_disabled_roles'
    | 'message_builder'
    | 'customize_message'
    | 'edit_message'
    | 'about_this_settings'
    | 'notifications'
    | 'manage_account'


    | 'site_settings'

    | 'design_and_appearance'
    | 'device_theme'
    | 'light_theme'
    | 'dark_theme'

    | 'language'
    | 'japanese'
    | 'english';

export type Translations = { [key in TranslationKeys]: ReactNode };

export interface Localization {
    locale: LocaleType;
    translations: Translations;
}

export interface LocalizationProps {
    localization: Localization;
}

