import { ReactNode } from 'react';

export type LocaleType = 'ja' | 'en';

export type TranslationKeys =
    'success'
    | 'warning'
    | 'error'
    | 'information'
    | 'loading'
    | 'login'
    | 'logout'
    | 'yes'
    | 'no'
    | 'enabled'
    | 'disabled'
    | 'default'
    | 'add'
    | 'remove'
    | 'create'
    | 'delete'
    | 'edit'
    | 'undo'
    | 'redo'
    | 'confirm'
    | 'cancel'
    | 'save'
    | 'reset'
    | 'discard_changes'
    | 'open'
    | 'close'
    | 'move_up'
    | 'move_down'
    | 'duplicate'


    | 'shard'
    | 'shards'
    | 'ping'
    | 'guild'
    | 'guilds'
    | 'channel'
    | 'channels'
    | 'role'
    | 'roles'
    | 'emoji'
    | 'emojis'
    | 'member'
    | 'members'
    | 'user'
    | 'users'


    | 'online'
    | 'offline'

    | 'status'
    | 'status_connecting'
    | 'status_connected'
    | 'status_disconnected'
    | 'status_waiting_reconnect'
    | 'status_reconnecting'
    | 'status_shutting_down'
    | 'status_shutdown'
    | 'status_failed_to_login'


    | 'permission'
    | 'permissions'

    | 'permissions_advanced'
    | 'permission_8'

    | 'permissions_general'
    | 'permission_32'
    | 'permission_16'
    | 'permission_268435456'
    | 'permission_536870912'
    | 'permission_1073741824'
    | 'permission_128'
    | 'permission_524288'
    | 'permission_2199023255552'
    | 'permission_1024'

    | 'permissions_membership'
    | 'permission_1'
    | 'permission_67108864'
    | 'permission_134217728'
    | 'permission_1099511627776'
    | 'permission_2'
    | 'permission_4'

    | 'permissions_text'
    | 'permission_2048'
    | 'permission_4096'
    | 'permission_70368744177664'
    | 'permission_65536'
    | 'permission_32768'
    | 'permission_16384'
    | 'permission_262144'
    | 'permission_137438953472'
    | 'permission_64'
    | 'permission_131072'
    | 'permission_8192'
    | 'permission_2147483648'

    | 'permissions_thread'
    | 'permission_274877906944'
    | 'permission_34359738368'
    | 'permission_68719476736'
    | 'permission_17179869184'

    | 'permissions_voice'
    | 'permission_1048576'
    | 'permission_2097152'
    | 'permission_512'
    | 'permission_549755813888'
    | 'permission_4398046511104'
    | 'permission_35184372088832'
    | 'permission_33554432'
    | 'permission_256'
    | 'permission_4194304'
    | 'permission_8388608'
    | 'permission_16777216'

    | 'permissions_stage'
    | 'permission_4294967296'

    | 'permissions_events'
    | 'permission_8589934592'


    | 'pattern_date'
    | 'pattern_time'
    | 'pattern_datetime'


    | 'search'
    | 'search_channels'
    | 'search_roles'
    | 'search_members'


    | 'embeds'
    | 'embed'
    | 'embed_add'
    | 'embed_author'
    | 'embed_author_name'
    | 'embed_author_url'
    | 'embed_author_icon_url'
    | 'embed_body'
    | 'embed_body_title'
    | 'embed_body_description'
    | 'embed_body_url'
    | 'embed_body_color'
    | 'embed_fields'
    | 'embed_field'
    | 'embed_field_add'
    | 'embed_field_name'
    | 'embed_field_value'
    | 'embed_field_inline'
    | 'embed_image'
    | 'embed_image_image_url'
    | 'embed_image_thumbnail_url'
    | 'embed_footer'
    | 'embed_footer_text'
    | 'embed_footer_icon_url'
    | 'embed_footer_timestamp'


    | 'error_unauthorized_title'
    | 'error_unauthorized_description'
    | 'error_forbidden_title'
    | 'error_forbidden_description'
    | 'error_not_found_title'
    | 'error_not_found_description'


    | 'welcome'
    | 'welcome_to_name'


    | 'home'
    | 'back_to_home'


    | 'status_description'
    | 'status_all_connected'
    | 'status_any_connected'
    | 'status_all_disconnected'
    | 'status_shard_with_id'
    | 'status_average_ping'
    | 'status_mutual_guilds'
    | 'status_mutual_guilds_with_count'
    | 'status_mutual_guilds_empty'
    | 'status_mutual_guilds_not_logged_in'


    | 'leaderboard'
    | 'leaderboard_description'


    | 'dashboard'
    | 'dashboard_error_manage_roles_empty_dialog_title'
    | 'dashboard_error_manage_roles_empty_dialog_description'
    | 'dashboard_error_cannot_be_enabled_alert_title'


    | 'guild_settings'
    | 'guild_settings_description'
    | 'add_bot'
    | 'back_to_select_guild'
    | 'settings_basic'
    | 'settings_guild_management'
    | 'settings_moderation_and_management'
    | 'settings_features_and_options'

    | 'prefix_and_nickname'
    | 'prefix_and_nickname_description'
    | 'prefix'
    | 'nickname'
    | 'nickname_description'

    | 'time_and_language'
    | 'guild_time_and_language_description'
    | 'date_and_time'
    | 'timezone'
    | 'timezone_description'
    | 'guild_language_description'

    | 'commands'
    | 'commands_description'
    | 'commands_permissions_channels'
    | 'commands_permissions_all_channels'
    | 'commands_permissions_roles'
    | 'commands_permissions_all_roles'
    | 'commands_permissions_members'
    | 'command_manage'
    | 'command_enabled'
    | 'command_user_permissions'
    | 'command_bot_permissions'
    | 'command_permissions_channels'
    | 'command_permissions_roles'
    | 'command_permissions_members'

    | 'automod'

    | 'role_permissions'
    | 'role_permissions_description'
    | 'role_permissions_select_roles'
    | 'role_permissions_how_to'
    | 'role_permissions_how_to_description_yes'
    | 'role_permissions_how_to_description_no'
    | 'role_permissions_how_to_description_inherited_everyone'
    | 'role_permissions_how_to_description_inherited_administrator'
    | 'role_permissions_how_to_description_deletable'
    | 'role_permissions_grid_yes'
    | 'role_permissions_grid_no'
    | 'role_permissions_grid_inherited_everyone'
    | 'role_permissions_grid_inherited_administrator'
    | 'role_permissions_grid_deletable'

    | 'welcome_message'
    | 'welcome_message_description'
    | 'welcome_message_enabled'
    | 'welcome_message_edit_description'
    | 'welcome_message_edit_hint'

    | 'goodbye_message'
    | 'goodbye_message_description'
    | 'goodbye_message_enabled'
    | 'goodbye_message_edit_description'
    | 'goodbye_message_edit_hint'

    | 'member_join'
    | 'member_join_description'
    | 'member_join_enabled'
    | 'member_join_before_pending'
    | 'member_join_before_pending_enabled'
    | 'member_join_before_pending_message_enabled'
    | 'member_join_before_pending_message_edit_description'
    | 'member_join_before_pending_roles_enabled'
    | 'member_join_before_pending_role_type_everyone'
    | 'member_join_before_pending_role_type_user'
    | 'member_join_before_pending_role_type_bot'
    | 'member_join_before_pending_role_type_verified_bot'
    | 'member_join_before_pending_role_type_not_verified_bot'
    | 'member_join_after_pending'
    | 'member_join_after_pending_error_cannot_be_enabled_alert_description'
    | 'member_join_after_pending_enabled'
    | 'member_join_after_pending_message_enabled'
    | 'member_join_after_pending_message_edit_description'
    | 'member_join_after_pending_roles_enabled'
    | 'member_join_message'
    | 'member_join_message_edit_hint'
    | 'member_join_roles'
    | 'member_join_manage_roles'

    | 'activity'
    | 'activity_description'
    | 'activity_enabled'
    | 'activity_manage_roles'
    | 'activity_type'
    | 'activity_type_playing_long'
    | 'activity_type_playing_short'
    | 'activity_type_playing_description'
    | 'activity_type_streaming_long'
    | 'activity_type_streaming_short'
    | 'activity_type_streaming_description'
    | 'activity_type_listening_long'
    | 'activity_type_listening_short'
    | 'activity_type_listening_description'
    | 'activity_type_watching_long'
    | 'activity_type_watching_short'
    | 'activity_type_watching_description'
    | 'activity_type_custom_status_long'
    | 'activity_type_custom_status_short'
    | 'activity_type_custom_status_description'

    | 'role_panels'

    | 'level'
    | 'experience'
    | 'rank'
    | 'level_error_invalid_type_level_or_experience'
    | 'level_description'
    | 'level_enabled'
    | 'level_experience_per_message'
    | 'level_manage'
    | 'level_manage_disabled_channels_description'
    | 'level_manage_disabled_roles_description'
    | 'level_reward'
    | 'level_reward_type'
    | 'level_reward_type_stack'
    | 'level_reward_type_stack_description'
    | 'level_reward_type_replace'
    | 'level_reward_type_replace_description'
    | 'level_reward_remove_role_demoted'
    | 'level_reward_manage_roles'
    | 'level_notification'
    | 'level_notification_type'
    | 'level_notification_type_disabled'
    | 'level_notification_type_direct_message'
    | 'level_notification_type_latest_channel'
    | 'level_notification_type_custom_channel'
    | 'level_notification_channel'
    | 'level_notification_edit_description'
    | 'level_notification_edit_hint'
    | 'level_leaderboard'
    | 'level_leaderboard_view'
    | 'level_leaderboard_public'
    | 'level_leaderboard_allow_join'
    | 'level_leaderboard_vanity_code'

    | 'translate'
    | 'translate_description'
    | 'translate_enabled'
    | 'translate_reaction'
    | 'translate_manage_disabled_channels_description'
    | 'translate_manage_disabled_roles_description'

    | 'vote'
    | 'vote_description'
    | 'vote_enabled'
    | 'quote'
    | 'quote_description'
    | 'quote_enabled'
    | 'quote_reaction'
    | 'quote_message'
    | 'quote_other_guild_to_this_guild'
    | 'quote_this_guild_to_other_guild'
    | 'quote_manage_disabled_channels_description'
    | 'quote_manage_disabled_roles_description'

    | 'music'
    | 'music_description'
    | 'music_enabled'
    | 'music_web_panel'
    | 'music_default_volume'
    | 'music_timeout_seconds'
    | 'music_next_media_notification'
    | 'music_next_media_notification_description'
    | 'music_sources'
    | 'music_source_youtube'
    | 'music_source_youtube_error_cannot_be_enabled_alert_description'
    | 'music_source_niconico'
    | 'music_source_soundcloud'
    | 'music_source_twitch'
    | 'music_source_bandcamp'
    | 'music_source_vimeo'

    | 'text_to_speech'

    | 'logging'
    | 'logging_description'
    | 'logging_enabled'
    | 'logging_channel'
    | 'logging_moderation'
    | 'logging_moderation_update'
    | 'logging_moderation_kick'
    | 'logging_moderation_prune'
    | 'logging_moderation_ban'
    | 'logging_moderation_unban'
    | 'logging_member'
    | 'logging_member_join'
    | 'logging_member_leave'
    | 'logging_member_update'
    | 'logging_member_role_add'
    | 'logging_member_role_remove'
    | 'logging_voice'
    | 'logging_voice_join'
    | 'logging_voice_leave'
    | 'logging_voice_move'
    | 'logging_voice_mute'
    | 'logging_voice_deafen'
    | 'logging_category'
    | 'logging_text_channel'
    | 'logging_voice_channel'
    | 'logging_channel_permission_update'
    | 'logging_role'
    | 'logging_emote'
    | 'logging_invite'
    | 'logging_webhook'
    | 'logging_integration'
    | 'logging_object_create'
    | 'logging_object_delete'
    | 'logging_object_update'
    | 'logging_message'
    | 'logging_message_update'
    | 'logging_message_delete'
    | 'logging_message_purge'
    | 'logging_message_pin'
    | 'logging_message_unpin'


    | 'user_settings'
    | 'user_time_and_language_description'
    | 'user_language_description'


    | 'save_confirm'
    | 'save_confirm_changes'
    | 'save_confirm_issues'

    | 'save_confirm_data'
    | 'save_confirm_settings'
    | 'save_confirm_settings_error_cannot_save_alert_title'
    | 'save_confirm_settings_error_cannot_save_alert_description'


    | 'statistics'
    | 'statistics_description'
    | 'statistics_mode'
    | 'statistics_mode_hours'
    | 'statistics_mode_days'
    | 'statistics_mode_weeks'
    | 'statistics_mode_months'
    | 'statistics_period'
    | 'statistics_period_from'
    | 'statistics_period_to'
    | 'statistics_widget_live'
    | 'statistics_widget_min'
    | 'statistics_widget_max'
    | 'statistics_table_date'
    | 'statistics_table_total'
    | 'statistics_table_shard_with_id'


    | 'send_message_channel'
    | 'manage_disabled_channels'
    | 'manage_disabled_roles'


    | 'message_builder'
    | 'message_builder_editor'
    | 'message_builder_preview'
    | 'message_builder_light_theme'
    | 'message_builder_dark_theme'
    | 'message_builder_cozy_mode'
    | 'message_builder_compact_mode'

    | 'customize_message'
    | 'edit_message'


    | 'about_this_settings'


    | 'lunaproject_services'
    | 'lunaproject_document'
    | 'lunaproject_account'


    | 'notifications'


    | 'manage_account'

    | 'site_settings'

    | 'design_and_appearance'
    | 'device_theme'
    | 'light_theme'
    | 'dark_theme'

    | 'language'
    | 'japanese'
    | 'english';

export type Translations = { [key in TranslationKeys]: ReactNode };

export interface Localization {
    locale: LocaleType;
    translations: Translations;
}

export interface LocalizationProps {
    localization: Localization;
}

